src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=555)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $planified_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $socialMedia;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function getSocialMedia()
    {
        return $this->socialMedia;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPlanifiedAt(): ?\DateTimeInterface
    {
        return $this->planified_at;
    }

    public function setPlanifiedAt(?\DateTimeInterface $planified_at): self
    {
        $this->planified_at = $planified_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function setSocialMedia(string $socialMedia): self
    {
        $this->socialMedia = $socialMedia;

        return $this;
    }
}

src/Controller/MessageController.php
<?php

namespace App\Controller;

use App\Client\DiscordClientInterface;
use App\Client\SlackClientInterface;
use App\Entity\Message;
use App\Entity\Status;
use App\Form\MessageFormType;
use App\Repository\MessageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/message", name="message_")
 */
class MessageController extends AbstractController
{

    private $security;
    CONST SLACK = 'Slack';
    CONST DISCORD = 'Discord';
    CONST SENT = 'sent';
    CONST PLANIFIED = 'planified';

    public function __construct(
        Security               $security,
        SlackClientInterface   $slackClient,
        DiscordClientInterface $discordClient
    )
    {
        $this->security = $security;
        $this->slackClient = $slackClient;
        $this->discordClient = $discordClient;
    }

    /**
     * @Route("/new", name="new")
     */
    public function newMessage(Request $req, EntityManagerInterface $em): Response
    {
        $message = new Message();
        $form = $this->createForm(MessageFormType::class, $message);
        $form->handleRequest($req);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->security->getUser();

            $message->setUserId($user);
            ($message->getPlanifiedAt() != null) ? $message->setStatus(MessageController::PLANIFIED) : $message->setStatus(MessageController::SENT);
            $message->setCreatedAt(new \DateTimeImmutable('now'));

            $em->persist($message);
            $em->flush();

            if ($message->getSocialMedia() == MessageController::SLACK) {
                $this->slackClient->executeRequest($message->getContent());
            } elseif ($message->getSocialMedia() == MessageController::DISCORD) {
                $this->discordClient->executeRequest($message->getContent());
            } else {
                $this->slackClient->executeRequest($message->getContent());
                $this->discordClient->executeRequest($message->getContent());
            }

            $this->addFlash('success', 'Message envoyé avec succès !');

            return $this->redirectToRoute('app_index');
        }

        return $this->render('message/new.html.twig', [
            'messageForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/sent", name="sent", methods={"GET"})
     */
    public function messagesSent(MessageRepository $messageRepo): Response
    {
        $user = $this->security->getUser();
        return $this->render('message/sent.html.twig', [
            'messages' => $messageRepo->findBy(
                ['user_id' => $user, 'status' => 'sent'],
                ['created_at' => 'DESC']
            ),
        ]);
    }

    /**
     * @Route("/planified", name="planified", methods={"GET"})
     */
    public function messagesPlanified(MessageRepository $messageRepo): Response
    {
        $user = $this->security->getUser();
        return $this->render('message/planified.html.twig', [
            'messages' => $messageRepo->findBy(
                ['user_id' => $user, 'status' => 'planified'],
                ['created_at' => 'DESC']
            )
        ]);
    }
}

templates/message/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} | Message {% endblock %}

{% block body %}

    {% set formErrors = messageForm.vars.errors.form.getErrors(true) %}

    {% if formErrors|length %}
        <ul>
            {% for error in formErrors %}
                <li class="text-danger list-unstyled text-center font-weight-bold p-3">{{ error.message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9 col-sm-12">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="p-5">
                            {{ form_start(messageForm, { 'attr': { 'class': 'user' }}) }}

                            <div class="form-group text-center">
                                {{ form_label(messageForm.content) }}
                                {{ form_widget(messageForm.content) }}
                            </div>
                            {{ form_row(messageForm.planified_at) }}
                            <div class="form-group text-center">
                                {{ form_row(messageForm.socialMedia) }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-block col-lg-6 mx-auto mt-4">
                                Envoyer <i class="fas fa-paper-plane rotate-15 ml-1"></i>
                            </button>
                            {{ form_end(messageForm) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/message/planified.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} | Messages Planifiés {% endblock %}

{% block body %}

    <div class="mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            Messages Planifiés
        </h1>
    </div>

    {% if messages is empty %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <p class="h6 text-gray-800">
                Il n'y a aucun message à afficher. <a href="{{ path('message_new') }}">Cliquez ici</a> pour en ajouter
            </p>
        </div>
    {% endif %}

    {% for message in messages %}
        {% if app.user.id == message.userId.id %}
            <div class="row">
                <div class="col-xl-9 col-md-9 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body px-3 py-2">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        {{ app.user.firstName }} {{ app.user.lastName }}
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        {{ message.content }}
                                    </div>
                                </div>
                                <div class="col-auto">
                                    {% if date(message.createdAt) < date('-1day') %}
                                        {{ message.createdAt|date('d/m/Y H:m') }}
                                    {% else %}
                                        {{ message.createdAt|date('H:m') }}
                                    {% endif %}
                                    {% if message.socialMedia == 'Slack & Discord' %}
                                        | <i class="fab fa-slack text-gray-800"></i> & <i
                                            class="fab fa-discord text-gray-800"></i>
                                    {% elseif message.socialMedia == 'Discord' %}
                                        | <i class="fab fa-discord text-gray-800"></i>
                                    {% else %}
                                        | <i class="fab fa-slack text-gray-800"></i>
                                    {% endif %}
                                    | <i class="fas fa-check text-gray-800"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/message/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} | Messages Envoyés {% endblock %}

{% block body %}

    <div class="mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            Messages Envoyés
        </h1>
    </div>

    {% if messages is empty %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <p class="h6 text-gray-800">
                Il n'y a aucun message à afficher. <a href="{{ path('message_new') }}">Cliquez ici</a> pour en ajouter
            </p>
        </div>
    {% endif %}

    {% for message in app.flashes('success') %}
        <div id="alert" class="col-xl-9 col-md-9 mb-4 alert alert-success font-weight-bold">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in messages %}
        {% if app.user.id == message.userId.id %}
            <div class="row">
                <div class="col-xl-9 col-md-9 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body px-3 py-2">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        {{ app.user.firstName }} {{ app.user.lastName }}
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        {{ message.content }}
                                    </div>
                                </div>
                                <div class="col-auto">
                                    {% if date(message.createdAt) < date('-1day') %}
                                        {{ message.createdAt|date('d/m/Y H:m') }}
                                    {% else %}
                                        {{ message.createdAt|date('H:m') }}
                                    {% endif %}
                                    {% if message.socialMedia == 'Slack & Discord' %}
                                        | <i class="fab fa-slack text-gray-800"></i> & <i
                                            class="fab fa-discord text-gray-800"></i>
                                    {% elseif message.socialMedia == 'Discord' %}
                                        | <i class="fab fa-discord text-gray-800"></i>
                                    {% else %}
                                        | <i class="fab fa-slack text-gray-800"></i>
                                    {% endif %}
                                    | <i class="fas fa-check text-gray-800"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    <script>
        let successMsg = document.querySelector('#alert');
        setTimeout(function() {
            successMsg.remove();
        }, 3000)
    </script>
{% endblock %}